config/routes.rb
Rails.application.routes.draw do
  root 'owners#index'
  resources :owners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)

    if @owner.save
      redirect_to @owner
    else
      render 'new'
    end
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])

    if @owner.update(owner_params)
      redirect_to owners_path
    else
      render 'edit'
    end
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy

    redirect_to owners_path
  end

  private
    def owner_params
      params.require(:owner).permit(:name, :serial, :email, :country, :asset_serial, :asset_type, :expiration_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/assets/_buttons.html.erb
<div class='buttonContainer'>
  <button> 
    <i title='Show' class="fa-regular fa-eye fa-xl"></i>
  </button>              
  <button>
    <i title='Update' class="fa-solid fa-pen-to-square fa-xl"></i>
  </button>
  <%= button_to asset_path(asset), 
    method: :delete, 
    data: {
      confirm: 'Are you sure?'
    } do %>
    <i title='Delete' class="fa-solid fa-trash-can fa-xl"></i>
  <% end %>
</div>

app/views/assets/index.html.erb
<h1>Assets for company #001727</h1>
<div class='mainContainer'>  
  <div class='tableContainer'>
    <table>
      <thead>
        <tr>
          <th>NAME</th>
          <th>USER_SERIAL</th>
          <th>EMAIL</th>
          <th>COUNTRY</th>
          <th>ASSET_SERIAL</th>
          <th>ASSET_TYPE</th>
          <th>EXPIRATION_DATE</th>
          <th>ACTIONS</th>
        </tr>
      </thead>
      <tbody>
        <% @assets.each do |asset| %>
          <tr>
            <td><%= asset.name %></td>
            <td><%= asset.user_serial %></td>
            <td><%= asset.email %></td>
            <td><%= asset.country %></td>
            <td><%= asset.asset_serial %></td>
            <td class='assetType'>
              <% if asset.asset_type.eql?('Desktop') %>
                <i title='Desktop' class="fa-solid fa-computer fa-xl"></i>
              <% end %>
              <% if asset.asset_type.eql?('Laptop') %>
                <i title='Laptop' class="fa-solid fa-laptop fa-xl"></i>
              <% end %>
              <% if asset.asset_type.eql?('Mac') %>
                <i title='MacBook' class="fa-brands fa-apple fa-xl"></i>
              <% end %>
            </td>
            <td><%= asset.expiration_date %></td>
            <td> <%= render partial: 'buttons', :locals => {:asset => asset} %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/_asset-types.html.erb
<% if asset_type.eql?('Desktop') %>
  <i title='Desktop' class="fa-solid fa-computer fa-xl"></i>
<% end %>
<% if asset_type.eql?('Laptop') %>
  <i title='Laptop' class="fa-solid fa-laptop fa-xl"></i>
<% end %>
<% if asset_type.eql?('Mac') %>
  <i title='MacBook' class="fa-brands fa-apple fa-xl"></i>
<% end %>

app/views/owners/_buttons.html.erb
<div class='button-container'>
  <%= button_to owner_path(owner), method: :get, class: 'action-btn' do %>
    <i title='Show' class="fa-regular fa-eye fa-xl"></i>
  <% end %>
  <%= button_to edit_owner_path(owner), method: :get, class: 'action-btn' do %>
    <i title='Update' class="fa-solid fa-pen-to-square fa-xl"></i>
  <% end %>
  <%= button_to owner_path(owner), method: :delete, data: {confirm: 'Are you sure?'}, class: 'action-btn' do %>
    <i title='Delete' class="fa-solid fa-trash-can fa-xl"></i>
  <% end %>
</div>

app/views/owners/_form.html.erb
<%= form_with model: owner, class: 'form-container' do |f| %>
  <legend><%= "#{type} ##{owner.serial}" %></legend>
  <%= f.label :name, class: 'bold' %><br>
  <%= f.text_field :name %>
  <%= f.label :serial, class: 'bold' %><br>
  <%= f.text_field :serial %>
  <%= f.label :email, class: 'bold' %><br>
  <%= f.text_field :email %>
  <%= f.label :country, class: 'bold' %><br>
  <%= f.text_field :country %>
  <%= f.label :asset_serial, class: 'bold' %><br>
  <%= f.text_field :asset_serial %>
  <%= f.label :asset_type, class: 'bold' %><br>
  <%= f.text_field :asset_type %>
  <%= f.label :expiration_date, class: 'bold' %><br>
  <%= f.text_field :expiration_date %>
  <%= f.submit "#{type} Owner", :class => 'primary-button' %>
<%= link_to 'Go back', owners_path, class: 'go-back' %>
<% end %>

app/views/owners/_show-actions.html.erb
<%= button_to edit_owner_path(owner), method: :get, class: 'action-btn' do %>
  <i title='Update' class="fa-solid fa-pen-to-square fa-2xl"></i>
<% end %>
<%= button_to owner_path(owner), method: :delete, data: {confirm: 'Are you sure?'}, class: 'action-btn' do %>
  <i title='Delete' class="fa-solid fa-trash-can fa-2xl"></i>
<% end %>

app/views/owners/edit.html.erb
<div class='main-container'>
  <%= render partial: 'form', :locals => {:owner => @owner, :type => 'Update' } %>
</div>

app/views/owners/index.html.erb
<div class='main-container'>
  <h1>Inventory for company #001727</h1>
  <div class='top-action-bar'>
    <%= button_to new_owner_path, method: :get, class: 'add-new-btn' do %>
      <i title='Add new owner' class="fa-solid fa-plus mr-1"></i><span>Add New Owner</span>
    <% end %>
  </div>
  <div class='table-container'>
    <table>
      <thead>
        <tr>
          <th>NAME</th>
          <th>SERIAL</th>
          <th>EMAIL</th>
          <th>COUNTRY</th>
          <th>ASSET_SERIAL</th>
          <th>ASSET_TYPE</th>
          <th>EXPIRATION_DATE</th>
          <th>ACTIONS</th>
        </tr>
      </thead>
      <tbody>
        <% @owners.each do |owner| %>
          <tr>
            <td><%= owner.name %></td>
            <td><%= owner.serial %></td>
            <td><%= owner.email %></td>
            <td><%= owner.country %></td>
            <td><%= owner.asset_serial %></td>
            <td>
              <%= render partial: 'asset-types', :locals => {:asset_type => owner.asset_type} %>
            </td>
            <td><%= owner.expiration_date %></td>
            <td> <%= render partial: 'buttons', :locals => {:owner => owner} %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/owners/new.html.erb
<div class='main-container'>
  <%= render partial: 'form', :locals => {:owner => @owner, :type => 'New' } %>
</div>

app/views/owners/show.html.erb
<div class='main-container'>
  <form class='form-container'>
  <legend>Owner #<%= @owner.serial %></legend>
    <div class='kv-container'>
      <strong>Name:</strong>
      <div class='value'>
        <%= @owner.name %>
      </div>
    </div>

    <div class='kv-container'>
      <strong>Email:</strong>
      <div class='value'>
        <%= @owner.email %>
      </div>
    </div>

    <div class='kv-container'>
      <strong>Country:</strong>
      <div class='value'>
        <%= @owner.country %>
      </div>
    </div>

    <div class='kv-container'>
      <strong>Asset serial:
        <%= render partial: 'asset-types', :locals => {:asset_type => @owner.asset_type} %>
      </strong>
      <div class='value'>
        <%= @owner.asset_serial %>
      </div>

    </div>

    <div class='kv-container'>
      <strong>Expiration date:</strong>
      <div class='value'>
        <%= @owner.expiration_date %>
      </div>
    </div>
    <%= link_to 'Go back', owners_path, class: 'go-back font-lg' %>
    <div class='show-actions button-container'>
      <%= render partial: 'show-actions', :locals => {:owner => @owner} %>
    </div>
  </form>
</div>